version: 2.0
jobs:
  test-locally:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install .

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
      # https://circleci.com/docs/2.0/google-auth/
      # https://circleci.com/docs/2.0/google-container-engine/
      # https://cloud.google.com/container-registry/docs/pushing
  push-image:
    machine: true
    steps:
      - checkout
      - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
      - run: docker build --rm=false -t eu.gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1 .
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run: gcloud --quiet config set project ${GCP_PROJECT}
      - run: gcloud docker -- push eu.gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1
  deploy-image:
    machine: true
    steps:
      - checkout
      - run: 
          name: Deploy app to Google via Docker
          command: |
            ssh -o StrictHostKeyChecking=no cst2989@34.91.197.175 "/bin/bash ./deploy_app.sh eu.gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1"
# see https://circleci.com/docs/2.0/workflows/
workflows:
  version: 2
  test-and-build-image:
    jobs:
      - test-locally
      - push-image:
          filters:
            branches:
              only:
                - master
          requires:
            - test-locally
      - deploy-image:
          filters:
            branches:
              only:
                - master
          requires:
            - test-locally
            - push-image